"""Generate provider-specific Agent Skills from approved, provider-neutral rules."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from ruleloom.config import RuleLoomConfig
from ruleloom.models import Candidate, ModelError
from ruleloom.storage import load_approved, project_path, write_text

GENERATED_MARKER = "<!-- Generated by RuleLoom. Edit the approved candidate, then re-sync. -->"
_MAX_GENERATED_SKILL_BYTES = 2 * 1024 * 1024


@dataclass(frozen=True, slots=True)
class SyncResult:
    path: Path
    changed: bool


def _skill_text() -> str:
    return f"""---
name: ruleloom
description: Apply approved, evidence-backed RuleLoom policies when changing this repository.
---

{GENERATED_MARKER}

# RuleLoom policies

Use this skill for code changes in this repository.

1. Give the change a stable independent-unit id (for example, its PR or task id) and reuse it
   across repeated assessments. Before finishing uncommitted work, run
   `ruleloom assess --base HEAD --change-id <stable-change-id>`; it assesses the working tree
   by default. For two committed revisions, also pass `--head <revision>`.
2. This skill contains approved policies only. Approved-policy assessments may show facts and
   rule matches normally; do not pass `--blind` or `--include-shadow` in an agent workflow.
3. Read only the matching rules reported by the command and
   [the approved rule cards](references/approved-rules.md).
4. Treat a match as an advisory request for additional validation, not proof of a defect.
5. Cite the candidate id and matching facts in your summary.
6. If RuleLoom abstains, do not invent or generalize a repository policy.
7. Never promote, approve, edit, or delete a RuleLoom policy without explicit human review.

Shadow policies are never synchronized into this skill or its rule cards. Shadow assessment is a
separate blind pilot workflow and must not influence the coding agent.

Facts and labels have different roles: facts describe the change at prediction time; labels are
later outcomes used for learning. Never use CI/review outcomes as facts for an earlier prediction.
"""


def _rules_text(candidates: Sequence[Candidate]) -> str:
    lines = [GENERATED_MARKER, "", "# Approved RuleLoom rule cards", ""]
    if not candidates:
        lines.extend(
            [
                "No rule is approved. RuleLoom must abstain until a human approves a candidate.",
                "",
            ]
        )
        return "\n".join(lines)
    for candidate in candidates:
        test = candidate.metrics.get("test")
        lines.extend([f"## {candidate.id}", ""])
        if test is not None:
            lines.append(
                f"Temporal holdout: precision {test.precision:.3f}, recall {test.recall:.3f}, "
                f"MCC {test.matthews_correlation:.3f}; stability {candidate.stability:.3f}."
            )
            lines.append("")
        for clause in candidate.rules.clauses:
            conditions = " AND ".join(
                ("NOT " if literal.negated else "") + literal.predicate for literal in clause.body
            )
            lines.extend(
                [
                    f"- `{clause.to_prolog()}`",
                    f"  - Apply when: {conditions}.",
                    f"  - Advisory outcome: `{candidate.rules.target}`.",
                ]
            )
        lines.append("")
    return "\n".join(lines)


def _safe_sync(path: Path, content: str, *, check: bool) -> SyncResult:
    if len(content.encode("utf-8")) > _MAX_GENERATED_SKILL_BYTES:
        raise ModelError(
            f"generated agent skill exceeds {_MAX_GENERATED_SKILL_BYTES} bytes: {path}"
        )
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current is not None and GENERATED_MARKER not in current:
        raise ModelError(f"refusing to overwrite unmanaged agent file: {path}")
    changed = current != content
    if changed and not check:
        write_text(path, content)
    return SyncResult(path=path, changed=changed)


def sync_agents(
    root: Path,
    config: RuleLoomConfig,
    *,
    agents: Sequence[str] = ("codex", "claude"),
    check: bool = False,
) -> list[SyncResult]:
    """Materialize one portable skill for Codex and/or Claude Code."""
    unknown = set(agents).difference({"codex", "claude"})
    if unknown:
        raise ModelError(f"unsupported agents: {', '.join(sorted(unknown))}")
    approved = load_approved(root, config)
    results: list[SyncResult] = []
    relative_destinations = {
        "codex": (
            ".agents/skills/ruleloom/SKILL.md",
            ".agents/skills/ruleloom/references/approved-rules.md",
        ),
        "claude": (
            ".claude/skills/ruleloom/SKILL.md",
            ".claude/skills/ruleloom/references/approved-rules.md",
        ),
    }
    for agent in agents:
        skill_relative, rules_relative = relative_destinations[agent]
        skill_path = project_path(root, skill_relative)
        rules_path = project_path(root, rules_relative)
        results.append(_safe_sync(skill_path, _skill_text(), check=check))
        results.append(
            _safe_sync(
                rules_path,
                _rules_text(approved),
                check=check,
            )
        )
    return results
